version: '3.8'

services:
  web:
    build: .
    ports:
      - "2001:8000"
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,13.60.195.151,horizoneurope.io,email.horizoneurope.io,sender.horizoneurope.io
    volumes:
      - ./data:/app/data
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=email_sender_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
