# Generated by Django 5.2.5 on 2025-08-09 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Campaign name', max_length=200)),
                ('subject', models.TextField(help_text='Email subject used')),
                ('template', models.TextField(help_text='Email template used')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_count', models.IntegerField(default=0, help_text='Total emails sent')),
                ('delivered_count', models.IntegerField(default=0, help_text='Total emails delivered')),
                ('opened_count', models.IntegerField(default=0, help_text='Total emails opened')),
                ('clicked_count', models.IntegerField(default=0, help_text='Total emails clicked')),
                ('bounced_count', models.IntegerField(default=0, help_text='Total emails bounced')),
                ('complained_count', models.IntegerField(default=0, help_text='Total complaints')),
                ('failed_count', models.IntegerField(default=0, help_text='Total failed emails')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='Unique event ID from Resend', max_length=255, unique=True)),
                ('event_type', models.CharField(choices=[('email.sent', 'Email Sent'), ('email.delivered', 'Email Delivered'), ('email.bounced', 'Email Bounced'), ('email.opened', 'Email Opened'), ('email.clicked', 'Email Clicked'), ('email.complained', 'Email Complained'), ('email.failed', 'Email Failed'), ('email.delivery_delayed', 'Email Delivery Delayed'), ('email.scheduled', 'Email Scheduled'), ('contact.created', 'Contact Created'), ('contact.updated', 'Contact Updated'), ('contact.deleted', 'Contact Deleted'), ('domain.created', 'Domain Created'), ('domain.updated', 'Domain Updated'), ('domain.deleted', 'Domain Deleted')], help_text='Type of event', max_length=50)),
                ('created_at', models.DateTimeField(help_text='When the event occurred')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When we received the webhook')),
                ('email_id', models.CharField(blank=True, help_text='Email ID from Resend', max_length=255, null=True)),
                ('from_email', models.EmailField(blank=True, help_text='Sender email address', max_length=254, null=True)),
                ('to_email', models.EmailField(blank=True, help_text='Recipient email address', max_length=254, null=True)),
                ('subject', models.TextField(blank=True, help_text='Email subject', null=True)),
                ('click_url', models.URLField(blank=True, help_text='URL clicked (for click events)', null=True)),
                ('bounce_reason', models.TextField(blank=True, help_text='Reason for bounce', null=True)),
                ('complaint_feedback_type', models.CharField(blank=True, help_text='Type of complaint', max_length=100, null=True)),
                ('raw_data', models.JSONField(help_text='Complete webhook payload')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_type'], name='email_monit_event_t_6a13c0_idx'), models.Index(fields=['to_email'], name='email_monit_to_emai_f6ad88_idx'), models.Index(fields=['created_at'], name='email_monit_created_ae7310_idx'), models.Index(fields=['email_id'], name='email_monit_email_i_3d2b32_idx')],
            },
        ),
    ]
