# Generated by Django 5.2.5 on 2025-08-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailevent',
            name='event_id',
            field=models.CharField(help_text='Event ID from Resend (can be duplicate)', max_length=255),
        ),
    ]
