# Generated by Django 5.2.5 on 2025-08-09 18:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_monitor', '0002_alter_emailevent_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(help_text='Primary email address', max_length=254, unique=True)),
                ('verified_email', models.BooleanField(default=False, help_text='Whether email is verified')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('location_country', models.CharField(blank=True, max_length=100, null=True)),
                ('email_status', models.CharField(choices=[('not_sent', 'Not Sent Yet'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('failed', 'Failed')], default='not_sent', max_length=20)),
                ('last_email_sent', models.DateTimeField(blank=True, null=True)),
                ('last_opened', models.DateTimeField(blank=True, null=True)),
                ('last_clicked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('csv_data', models.JSONField(blank=True, help_text='Complete CSV row data', null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['email'], name='email_monit_email_51ab3f_idx'), models.Index(fields=['email_status'], name='email_monit_email_s_621219_idx'), models.Index(fields=['last_name', 'first_name'], name='email_monit_last_na_2ca9df_idx')],
            },
        ),
    ]
