# Generated by Django 5.2.5 on 2025-08-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_monitor', '0004_contact_company_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='verified_email',
        ),
    ]
