# Generated by Django 5.2.5 on 2025-08-11 00:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_monitor', '0005_remove_contact_verified_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('default', 'Default Template'), ('last_used', 'Last Used Template')], help_text='Type of template (default or last used)', max_length=20, unique=True)),
                ('subject', models.TextField(default='EU Grant Advisory Platform - Beta Testing Invitation', help_text='Email subject')),
                ('content', models.TextField(help_text='Email template content')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When template was last updated')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
