# Generated by Django 5.2.5 on 2025-08-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_monitor', '0006_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='sender',
            field=models.CharField(default='horizoneurope', help_text='Sender identifier (horizoneurope, horizon_eu, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('default', 'Default Template'), ('last_used', 'Last Used Template')], help_text='Type of template (default or last used)', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('template_type', 'sender')},
        ),
    ]
