# Generated by Django 5.2.5 on 2025-08-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_monitor', '0007_emailtemplate_sender_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contact',
            name='email_monit_email_s_621219_idx',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email_status',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_clicked',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_email_sent',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_opened',
        ),
    ]
