# Generated by Django 5.2.5 on 2025-08-12 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_monitor', '0008_remove_email_status_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='emailsender',
        ),
    ]
